import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useSunoGov } from '../context/SunoGovContext';
import { Card } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { Button } from '../components/ui/Button';
import { ArrowLeft, Check, Circle, Info, Loader2, AlertCircle, Bell, Sparkles } from 'lucide-react';
import { apiService } from '../services/api';
import { GrievanceStatus } from '../types';

// Tracking interface representing ticket checkpoints
export const Track: React.FC = () => {
  const navigate = useNavigate();
  const { refId, grievance, updateGrievance, resetJourney } = useSunoGov();

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Route guard
  useEffect(() => {
    if (!refId) {
      navigate('/');
    }
  }, [refId, navigate]);
  
  // Action states (Simulation, Reminders)
  const [actionLoading, setActionLoading] = useState<'status' | 'reminder' | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);
  const [reminderMessage, setReminderMessage] = useState<string | null>(null);

  // Status mapping setup
  const statusList: GrievanceStatus[] = [
    'SUBMITTED',
    'ACKNOWLEDGED',
    'UNDER_REVIEW',
    'REGIONAL_REVIEW',
    'RESOLVED'
  ];

  // Fetch grievance status on mount
  useEffect(() => {
    const fetchStatus = async () => {
      if (!refId) return;
      setLoading(true);
      setError(null);
      try {
        const result = await apiService.getGrievance(refId);
        updateGrievance(result);
      } catch (err: any) {
        setError(err.message || "We couldn't load your grievance right now.");
      } finally {
        setLoading(false);
      }
    };
    fetchStatus();
  }, [refId]);

  const handleBackHome = () => {
    resetJourney();
    navigate('/');
  };

  const handleSimulateStatus = async () => {
    if (!grievance) return;
    setActionLoading('status');
    setActionError(null);
    setReminderMessage(null);
    try {
      const result = await apiService.simulateStatus(grievance.id);
      updateGrievance(result);
    } catch (err: any) {
      setActionError(err.message || "We couldn't update the demo status.");
    } finally {
      setActionLoading(null);
    }
  };

  const handleSendReminder = async () => {
    if (!grievance) return;
    setActionLoading('reminder');
    setActionError(null);
    setReminderMessage(null);
    try {
      const result = await apiService.sendReminder(grievance.id);
      setReminderMessage(result.message || 'Demo reminder recorded.');
      // Refresh grievance data to get last_reminded_at timestamp
      const refreshed = await apiService.getGrievance(grievance.id);
      updateGrievance(refreshed);
    } catch (err: any) {
      setActionError(err.message || "Couldn't record the demo reminder.");
    } finally {
      setActionLoading(null);
    }
  };

  // Determine state of each timeline step
  const getStepState = (stepStatus: GrievanceStatus) => {
    if (!grievance) return 'upcoming';
    const currentIdx = statusList.indexOf(grievance.status);
    const stepIdx = statusList.indexOf(stepStatus);

    if (stepIdx < currentIdx) return 'completed';
    if (stepIdx === currentIdx) return 'current';
    return 'upcoming';
  };

  const timelineSteps = [
    { title: 'Submitted', desc: 'Simulated grievance record successfully created in backend.', status: 'SUBMITTED' as GrievanceStatus },
    { title: 'Acknowledged', desc: 'Mock acknowledgment generated by government desk.', status: 'ACKNOWLEDGED' as GrievanceStatus },
    { title: 'Under Review', desc: 'Assigned to simulated EPFO regional claims desk.', status: 'UNDER_REVIEW' as GrievanceStatus },
    { title: 'Regional Review', desc: 'Pending inspection by regional field officer.', status: 'REGIONAL_REVIEW' as GrievanceStatus },
    { title: 'Resolution', desc: 'Final response generated and ticket closed.', status: 'RESOLVED' as GrievanceStatus }
  ];

  // ----------------------------------------
  // Loading & Error Views
  // ----------------------------------------
  if (loading) {
    return (
      <div className="max-w-md mx-auto py-16 text-center space-y-4">
        <Loader2 className="w-10 h-10 text-primary-500 animate-spin mx-auto" />
        <p className="text-sm text-neutral-500">Loading grievance...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-md mx-auto space-y-6">
        <Card className="flex flex-col items-center p-6 text-center space-y-4">
          <AlertCircle className="w-12 h-12 text-red-500" />
          <h3 className="text-lg font-bold text-neutral-900">Error Loading Status</h3>
          <p className="text-sm text-neutral-600">
            {error}
          </p>
          <Button variant="primary" onClick={handleBackHome}>
            Return Home
          </Button>
        </Card>
      </div>
    );
  }

  const isResolved = grievance?.status === 'RESOLVED';

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      
      {/* Back Button */}
      <div className="flex items-center">
        <button
          onClick={handleBackHome}
          className="inline-flex items-center gap-1 text-sm font-semibold text-neutral-500 hover:text-neutral-700 focus:outline-none focus:underline"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to home
        </button>
      </div>

      {/* Main Track Card */}
      <Card className="space-y-6">
        
        {/* Header summary */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 border-b border-neutral-100 pb-5">
          <div className="space-y-1">
            <span className="text-[10px] font-bold text-neutral-400 uppercase tracking-wider block">Grievance Reference ID</span>
            <h2 className="text-xl font-black text-neutral-800 font-mono tracking-wide">{refId}</h2>
          </div>
          <Badge variant={isResolved ? 'success' : 'primary'}>
            {grievance?.status.replace('_', ' ')}
          </Badge>
        </div>

        {/* Info Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 bg-neutral-50 border border-neutral-100 rounded-xl p-4 text-sm">
          <div>
            <span className="text-[10px] font-bold text-neutral-400 uppercase tracking-wider block">Issue Category</span>
            <span className="text-neutral-800 font-bold">{grievance?.category}</span>
          </div>
          <div>
            <span className="text-[10px] font-bold text-neutral-400 uppercase tracking-wider block">Synthetic UAN Reference</span>
            <span className="text-neutral-800 font-bold font-mono">{grievance?.uan}</span>
          </div>
        </div>

        {/* Action feedback banners */}
        {actionError && (
          <div className="p-3 bg-red-50 border border-red-200 text-red-800 rounded-lg text-xs flex items-center gap-2">
            <AlertCircle className="w-4 h-4 text-red-600 shrink-0" />
            <span>{actionError}</span>
          </div>
        )}

        {reminderMessage && (
          <div className="p-3 bg-accent-50 border border-accent-200 text-accent-800 rounded-lg text-xs flex items-center gap-2">
            <Check className="w-4 h-4 text-accent-600 shrink-0" />
            <span>{reminderMessage}</span>
          </div>
        )}

        {/* Status Timeline */}
        <div className="space-y-8 relative pl-7 before:absolute before:left-3 before:top-2 before:bottom-2 before:w-0.5 before:bg-neutral-200">
          
          {timelineSteps.map((step) => {
            const state = getStepState(step.status);
            return (
              <div key={step.title} className="relative group">
                
                {/* Step Bullet Icon Indicator */}
                <div className="absolute -left-7 top-1 flex items-center justify-center">
                  {state === 'completed' && (
                    <div 
                      className="w-6.5 h-6.5 rounded-full bg-accent-500 text-white flex items-center justify-center ring-4 ring-accent-50"
                      aria-label="Completed"
                    >
                      <Check className="w-3.5 h-3.5 stroke-[3]" />
                    </div>
                  )}
                  {state === 'current' && (
                    <div 
                      className="w-6.5 h-6.5 rounded-full bg-primary-500 text-white flex items-center justify-center ring-4 ring-primary-100"
                      aria-label="In Progress"
                    >
                      <span className="w-2.5 h-2.5 rounded-full bg-white animate-pulse"></span>
                    </div>
                  )}
                  {state === 'upcoming' && (
                    <div 
                      className="w-6.5 h-6.5 rounded-full bg-white border-2 border-neutral-300 text-neutral-400 flex items-center justify-center"
                      aria-hidden="true"
                    >
                      <Circle className="w-2.5 h-2.5 fill-current text-transparent" />
                    </div>
                  )}
                </div>

                {/* Step Text Details */}
                <div className="pl-4">
                  <h3 className={`
                    text-sm font-bold leading-none
                    ${state === 'completed' ? 'text-neutral-800' : ''}
                    ${state === 'current' ? 'text-primary-700' : ''}
                    ${state === 'upcoming' ? 'text-neutral-400' : ''}
                  `}>
                    {step.title}
                  </h3>
                  <p className="text-xs text-neutral-500 mt-1.5 leading-relaxed">{step.desc}</p>
                </div>

              </div>
            );
          })}

        </div>

        {/* Prototype-only simulation control buttons */}
        <div className="border-t border-neutral-100 pt-5 flex flex-col sm:flex-row justify-end gap-3">
          
          <Button
            variant="outline"
            size="sm"
            onClick={handleSendReminder}
            disabled={actionLoading !== null || isResolved}
            className="w-full sm:w-auto border-neutral-300 gap-1.5 text-xs"
          >
            {actionLoading === 'reminder' ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <Bell className="w-3.5 h-3.5" />
            )}
            Send a reminder
          </Button>

          <Button
            variant="primary"
            size="sm"
            onClick={handleSimulateStatus}
            disabled={actionLoading !== null || isResolved}
            className="w-full sm:w-auto gap-1.5 text-xs bg-accent-500 hover:bg-accent-600"
          >
            {actionLoading === 'status' ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <Sparkles className="w-3.5 h-3.5" />
            )}
            Simulate next update
          </Button>

        </div>

        {grievance?.last_reminded_at && (
          <div className="text-[10px] text-right text-neutral-400 font-semibold italic">
            Last reminded at: {new Date(grievance.last_reminded_at).toLocaleString()}
          </div>
        )}

      </Card>

      {/* Tracker Status Notice */}
      <div className="p-4 bg-primary-50 border border-primary-100 text-primary-800 rounded-lg text-xs flex items-start gap-2.5">
        <Info className="w-4.5 h-4.5 text-primary-500 shrink-0 mt-0.5" />
        <div>
          <p className="font-semibold uppercase tracking-wide text-[10px] text-primary-900">Demo status simulation mode</p>
          <p className="mt-0.5 leading-relaxed">
            The status simulation controls allow stepping through review gates locally to preview visual progression. Reminders record timestamps on the mock grievance model.
          </p>
        </div>
      </div>

    </div>
  );
};
